### ISSUE TITLE
Rebuilding code and db locally I get error 

### ISSUE THREAD

**Issue by jfkproductions** [neo4j-graphacademy/llm-chatbot-python#13]
```
2024-08-01 16:13:27.848 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\KraaiduToit\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "C:\1.Pvt\1.Projects\llm-chatbot-python\bot.py", line 4, in <module>
    from agent import generate_response
  File "C:\1.Pvt\1.Projects\llm-chatbot-python\agent.py", line 13, in <module>
    from tools.vector import get_movie_plot
  File "C:\1.Pvt\1.Projects\llm-chatbot-python\tools\vector.py", line 19, in <module>
    neo4jvector = Neo4jVector.from_existing_index(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KraaiduToit\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_community\vectorstores\neo4j_vector.py", line 1209, in from_existing_index
    raise ValueError(
ValueError: The specified vector index name does not exist. Make sure to check if you spelled it correctly
2024-08-01 16:13:27.849 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\KraaiduToit\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "C:\1.Pvt\1.Projects\llm-chatbot-python\bot.py", line 4, in <module>
    from agent import generate_response
ImportError: cannot import name 'generate_response' from 'agent' (C:\1.Pvt\1.Projects\llm-chatbot-python\agent.py)
2024-08-01 16:13:27.849 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\KraaiduToit\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "C:\1.Pvt\1.Projects\llm-chatbot-python\bot.py", line 4, in <module>
    from agent import generate_response
ImportError: cannot import name 'generate_response' from 'agent' (C:\1.Pvt\1.Projects\llm-chatbot-python\agent.py)
```

which suggest the index does not exist if i do a show indexes I do see my index moviePlots did i recreate it wrongly if so how can I fix this 

<img width="931" alt="image" src="https://github.com/user-attachments/assets/72d83d1a-3d47-4eff-9c37-ca87b9fd5502">

here is he vectopr.py I am using 

```python
import streamlit as st
from llm import llm, embeddings
from graph import graph

# tag::import_vector[]
from langchain_community.vectorstores.neo4j_vector import Neo4jVector
# end::import_vector[]
# tag::import_chain[]
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain.chains import create_retrieval_chain
# end::import_chain[]

# tag::import_chat_prompt[]
from langchain_core.prompts import ChatPromptTemplate
# end::import_chat_prompt[]


# tag::vector[]
neo4jvector = Neo4jVector.from_existing_index(
    embeddings,                              # <1>
    graph=graph,                             # <2>
    index_name="moviePlots",                 # <3>
    node_label="Movie",                      # <4>
    text_node_property="plot",               # <5>
    embedding_node_property="plotEmbedding", # <6>
    retrieval_query="""
RETURN
    node.plot AS text,
    score,
    {
        title: node.title,
        directors: [ (person)-[:DIRECTED]->(node) | person.name ],
        actors: [ (person)-[r:ACTED_IN]->(node) | [person.name, r.role] ],
        tmdbId: node.tmdbId,
        source: 'https://www.themoviedb.org/movie/'+ node.tmdbId
    } AS metadata
"""
)
# end::vector[]

# tag::retriever[]
retriever = neo4jvector.as_retriever()
# end::retriever[]

# tag::prompt[]
instructions = (
    "Use the given context to answer the question."
    "If you don't know the answer, say you don't know."
    "Context: {context}"
)

prompt = ChatPromptTemplate.from_messages(
    [
        ("system", instructions),
        ("human", "{input}"),
    ]
)
# end::prompt[]

# tag::chain[]
question_answer_chain = create_stuff_documents_chain(llm, prompt)
plot_retriever = create_retrieval_chain(
    retriever, 
    question_answer_chain
)
# end::chain[]

# tag::get_movie_plot[]
def get_movie_plot(input):
    return plot_retriever.invoke({"input": input})
# end::get_movie_plot[]
```

**Comment by martinohanlon** [comment]
I have edited your issue to format the code. It was really difficult to read otherwise.

**Comment by martinohanlon** [comment]
The code and index both look ok. Are you sure your Python program is connecting to the same database?

**Comment by jpags77** [comment]
I am getting this same error; code on Gitpod, pasted directly from GraphAcademy. I restarted the course from scratch and ran into the same error...was also able to validate moviePlots index exists in the sandbox graph

![Screenshot 2024-11-17 at 3 53 06 PM](https://github.com/user-attachments/assets/d6fd629f-4c9b-4517-8271-0849c02a5e46)

![Screenshot 2024-11-17 at 3 53 41 PM](https://github.com/user-attachments/assets/48f68d39-8cf3-4955-8bb9-29414da5d1e5)

(https://github.com/user-attachments/files/17792370/export-2.csv)

**Comment by martinohanlon** [comment]
@jpags77 how did you create your vector index.

It is showing as a `RANGE` index:

```
6,moviePlots,ONLINE,100.0,RANGE,NODE,[Movie],[plotEmbedding],range-1.0,null,null,0`
```

At the start of the [Neo4j Vector Tool lesson](https://graphacademy.neo4j.com/courses/llm-chatbot-python/3-tools/1-vector-tool/) this script runs which imports the data and sets up the index - https://github.com/neo4j-graphacademy/courses/blob/main/asciidoc/courses/llm-chatbot-python/modules/3-tools/lessons/1-vector-tool/reset.cypher

I just tested this and I see a `VECTOR` index when running `show indexes`:

```
1,moviePlots,ONLINE,100.0,VECTOR,NODE,[Movie],[plotEmbedding],vector-2.0,null,null,0 
```

@jfkproductions - I missed this when you raised an issue but you seemed to have had a similar problem - i.e. a `RANGE` index was created not a `VECTOR`

**Comment by jpags77** [comment]
Hmm I ran the script against my sandbox DB but seems the moviePlots index didn't update, still showing as RANGE. I'll try deleting the moviePlots index and running the script again - noob alert! Thanks for your patience and engagement!

Definitely something weird going on because this was working initially when I went through the course, but after a few days this error started and has been persistent ever since. 

EDIT: IT WORKED! Had to drop the moviePlot range index, then the script created the vector index
